# Generated by Django 3.2.4 on 2021-09-28 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Variable_Unconstant',
            fields=[
                ('id_employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='payroll_app.employee_variable_constant')),
                ('name1', models.CharField(max_length=50)),
                ('name2', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Kobieta', 'Kobieta'), ('Mężczyzna', 'Mężczyzna')], max_length=200)),
                ('doc', models.CharField(choices=[('Paszport', 'Paszport'), ('Dowód osobisty', 'Dowód osobisty'), ('Prawo jazdy', 'Prawo jazdy')], max_length=200)),
                ('nr_doc', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('date_of_entry', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
