# Generated by Django 3.2.4 on 2021-09-28 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0002_employee_variable_unconstant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Variable_Unconstant_ARC',
            fields=[
                ('id_employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='payroll_app.employee_variable_constant')),
                ('name1', models.CharField(max_length=50)),
                ('name2', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Woman', 'Woman'), ('Man', 'Man')], max_length=200)),
                ('doc', models.CharField(choices=[('Passport', 'Passport'), ('ID card', 'ID card'), ('Driving license', 'Driving license')], max_length=200)),
                ('nr_doc', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('date_of_entry', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='List_of_Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name_of_proffession', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='employee_variable_unconstant',
            name='doc',
            field=models.CharField(choices=[('Passport', 'Passport'), ('ID card', 'ID card'), ('Driving license', 'Driving license')], max_length=200),
        ),
        migrations.AlterField(
            model_name='employee_variable_unconstant',
            name='gender',
            field=models.CharField(choices=[('Woman', 'Woman'), ('Man', 'Man')], max_length=200),
        ),
        migrations.CreateModel(
            name='Profession_ARC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name_of_proffession', models.CharField(max_length=100)),
                ('working_hours', models.CharField(max_length=30)),
                ('date_of_entry', models.DateTimeField(auto_now=True)),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.employee_variable_constant')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name_of_proffession', models.CharField(max_length=100)),
                ('working_hours', models.CharField(choices=[('Full time', 'Full time'), ('3/4', '3/4'), ('3/5', '3/5'), ('1/2', '1/2'), ('1/4', '1/4'), ('Unlimited', 'Unlimited')], max_length=30)),
                ('date_of_entry', models.DateTimeField(auto_now=True)),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.employee_variable_constant')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_contract', models.CharField(max_length=50)),
                ('date_of_start_work', models.DateField()),
                ('copyright_contract', models.BooleanField()),
                ('place_of_work', models.CharField(max_length=50)),
                ('main_place_of_work', models.BooleanField()),
                ('daily_norm', models.DecimalField(decimal_places=2, max_digits=4)),
                ('type_of_base_salary', models.CharField(max_length=50)),
                ('amount_of_base_salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('method_of_payment', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=26)),
                ('type_of_perks', models.CharField(max_length=50)),
                ('amount_of_perks', models.DecimalField(decimal_places=2, max_digits=7)),
                ('conclusion_of_the_contract', models.DateField()),
                ('company_representative', models.CharField(max_length=50)),
                ('contract_period', models.DateField()),
                ('id_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_app.employee_variable_constant')),
            ],
        ),
        migrations.CreateModel(
            name='Address_ARC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_address', models.CharField(choices=[('Constans', 'Constans'), ('Temporary', 'Temporary'), ('Correspondence', 'Correspondence'), ('Address of residence ', 'Address of residence')], max_length=100)),
                ('voivodeship', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('building_no', models.CharField(max_length=50)),
                ('apartment_no', models.CharField(blank=True, max_length=50, null=True)),
                ('post', models.CharField(max_length=50)),
                ('post_code', models.CharField(max_length=50)),
                ('date_of_entry', models.DateTimeField(auto_now=True)),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.employee_variable_constant')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_address', models.CharField(choices=[('Constans', 'Constans'), ('Temporary', 'Temporary'), ('Correspondence', 'Correspondence'), ('Address of residence ', 'Address of residence')], max_length=100)),
                ('voivodeship', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('building_no', models.CharField(max_length=50)),
                ('apartment_no', models.CharField(blank=True, max_length=50, null=True)),
                ('post', models.CharField(max_length=50)),
                ('post_code', models.CharField(max_length=50)),
                ('date_of_entry', models.DateTimeField(auto_now=True)),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.employee_variable_constant')),
            ],
        ),
    ]
