# Generated by Django 3.2.4 on 2021-09-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0003_auto_20210928_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='address_arc',
            name='type_of_change',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_of_start_work',
            field=models.DateField(null=True),
        ),
    ]
