# Generated by Django 3.2.4 on 2021-10-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0004_auto_20210930_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='type_of_change',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
