# Generated by Django 3.2.4 on 2021-10-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0007_auto_20211004_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_arc',
            name='date_of_exit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profession_arc',
            name='date_of_exit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
