# Generated by Django 3.2.4 on 2021-10-04 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0009_auto_20211004_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_variable_unconstant_arc',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_variable_unconstant_arc',
            name='id_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.employee_variable_constant'),
        ),
    ]
