# Generated by Django 3.2.7 on 2021-10-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0010_auto_20211004_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=100)),
                ('pl', models.CharField(max_length=100)),
            ],
        ),
    ]
