# Generated by Django 3.2.7 on 2021-10-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0011_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_variable_unconstant',
            name='name2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
