# Generated by Django 3.2.7 on 2021-10-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0012_alter_employee_variable_unconstant_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_variable_unconstant',
            name='doc',
            field=models.CharField(choices=[('Passport', 'Passport'), ('ID card', 'ID card'), ('Other', 'Other'), ('Driving license', 'Driving license')], max_length=200),
        ),
        migrations.AlterField(
            model_name='employee_variable_unconstant_arc',
            name='doc',
            field=models.CharField(choices=[('Passport', 'Passport'), ('ID card', 'ID card'), ('Driving license', 'Driving license'), ('Other', 'Other')], max_length=200),
        ),
    ]
