# Generated by Django 3.2.7 on 2021-10-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0013_auto_20211006_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_variable_unconstant_arc',
            name='name2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
