# Generated by Django 3.2.7 on 2021-10-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0015_auto_20211006_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_variable_unconstant',
            name='nationality',
            field=models.CharField(max_length=100),
        ),
    ]
