# Generated by Django 3.2.7 on 2021-10-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0021_alter_employee_variable_unconstant_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='account_number',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
