# Generated by Django 3.2.7 on 2021-10-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0022_alter_contract_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount_of_perks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='company_representative',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='copyright_contract',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='main_place_of_work',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
